on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PAT:
        required: true

jobs:

  tf2:
    if: inputs.build_tf2 == 'true'
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build Docker image
        run: cd steamcmd/tf2 && docker build -t beepsterr/tf2 --platform=linux/amd64 --progress=plain -f ./Dockerfile .

      - name: Push to package
        run: docker push beepsterr/tf2