on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PAT:
        required: true

jobs:

  jre17:
    needs: []
    uses: ./.github/workflows/build_java_jre17.yml
    secrets: inherit

  jre16:
    needs: []
    uses: ./.github/workflows/build_java_jre16.yml
    secrets: inherit

#  jre11:
#    needs: [ ]
#    uses: ./.github/workflows/build_java_jre17.yml
#    secrets: inherit
#
#  jre18:
#    needs: []
#    uses: ./.github/workflows/build_java_jre17.yml
#    secrets: inherit