name: Build Images

on:
  #push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:

  cleanup:
    runs-on: [self-hosted, linux]
    if: always()
    steps:
      - name: Cleanup
        run: docker image prune -a -f && docker volume prune -f

  proxy:
    uses: ./.github/workflows/build_proxy.yml
    secrets: inherit