name: Update Images

on:
  workflow_dispatch:

#inputs:
#  tf2:
#    type: boolean
#    description: 'Update TF2 image'
#  csgo:
#    type: boolean
#    description: 'Update CSGO image'
#  proxy:
#    type: boolean
#    description: 'Update Proxy image'
#  mc_119:
#    type: boolean
#    description: 'Update 1.19 Minecraft images'


jobs:

  proxy:
    uses: ./.github/workflows/build_proxy.yml