name: Build Images

on:
  #push:
  workflow_dispatch:
    inputs:
      build_proxy:
        description: 'Update Proxy Server'
        type: boolean
        default: false
      build_tf2:
        description: 'Update Team Fortress 2'
        type: boolean
        default: false
      build_csgo:
        description: 'Update Counter Strike: Global Offensive'
        type: boolean
        default: false
      build_mc_latest:
        description: 'Update Minecraft (Current Version)'
        type: boolean
        default: false
      build_mc_old:
        description: 'Update Minecraft (Previous Versions)'
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

jobs:

  proxy:
    if: github.event.inputs.build_proxy == 'true'
    uses: ./.github/workflows/build_proxy.yml
    secrets: inherit

  steamcmd:
    if: github.event.inputs.build_tf2 == 'true' || github.event.inputs.build_csgo == 'true'
    uses: ./.github/workflows/build_steamcmd.yml
    secrets: inherit

  tf2:
    if: github.event.inputs.build_tf2 == 'true'
    needs: steamcmd
    uses: ./.github/workflows/build_steam_tf2.yml
    secrets: inherit

  java:
    if: github.event.inputs.build_mc_latest == 'true' || github.event.inputs.build_mc_old == 'true'
    uses: ./.github/workflows/build_java.yml
    secrets: inherit

  minecraft_119:
    if: github.event.inputs.build_mc_latest == 'true'
    needs: java
    uses: ./.github/workflows/build_minecraft_1.19.yml
    secrets: inherit

  minecraft_118:
    if: github.event.inputs.build_mc_old == 'true'
    needs: java
    uses: ./.github/workflows/build_minecraft_1.18.yml
    secrets: inherit

  cleanup:
    runs-on: [self-hosted, linux]
    needs: [proxy, steamcmd, java]
    if: always()
    steps:
      - name: Cleanup
        run: docker image prune -a -f && docker volume prune -f