name: Build Images

on:
  #push:
  workflow_dispatch:
    inputs:
      build_proxy:
        description: 'Proxy Server'
        type: boolean
        default: false
      build_steamcmd:
        description: 'Update SteamCMD Image'
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

jobs:

  proxy:
    uses: ./.github/workflows/build_proxy.yml
    secrets: inherit

  steamcmd:
    uses: ./.github/workflows/build_steamcmd.yml
    secrets: inherit

  cleanup:
    runs-on: [self-hosted, linux]
    needs: [proxy, steamcmd]
    if: always()
    steps:
      - name: Cleanup
        run: docker image prune -a -f && docker volume prune -f