name: Build Images

on:
  #push:
  workflow_dispatch:
    inputs:
      build_proxy:
        description: 'Update Proxy Server'
        type: boolean
        default: false
      build_tf2:
        description: 'Update Team Fortress 2'
        type: boolean
        default: false
      build_mc_latest:
        description: 'Update Minecraft (Current Version)'
        type: boolean
        default: false
      build_mc_old:
        description: 'Update Minecraft (Previous Versions)'
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

jobs:

  proxy:
    uses: ./.github/workflows/build_proxy.yml
    secrets: inherit

  steamcmd:
    uses: ./.github/workflows/build_steamcmd.yml
    secrets: inherit

  java:
    needs:
    uses: ./.github/workflows/build_java.yml
    secrets: inherit

  cleanup:
    runs-on: [self-hosted, linux]
    needs: [proxy, steamcmd, java]
    if: always()
    steps:
      - name: Cleanup
        run: docker image prune -a -f && docker volume prune -f